name: user-statistician

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: dark
        # max-languages: 100
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
